package com.jkoss.pojo;

public class Producttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.typeId
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.typeName
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.fTypeId
     *
     * @mbggenerated
     */
    private String fTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.sTypeId
     *
     * @mbggenerated
     */
    private String sTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.Attribute_70
     *
     * @mbggenerated
     */
    private String attribute_70;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.typeId
     *
     * @return the value of producttype.typeId
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.typeId
     *
     * @param typeId the value for producttype.typeId
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.typeName
     *
     * @return the value of producttype.typeName
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.typeName
     *
     * @param typeName the value for producttype.typeName
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.fTypeId
     *
     * @return the value of producttype.fTypeId
     *
     * @mbggenerated
     */
    public String getfTypeId() {
        return fTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.fTypeId
     *
     * @param fTypeId the value for producttype.fTypeId
     *
     * @mbggenerated
     */
    public void setfTypeId(String fTypeId) {
        this.fTypeId = fTypeId == null ? null : fTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.sTypeId
     *
     * @return the value of producttype.sTypeId
     *
     * @mbggenerated
     */
    public String getsTypeId() {
        return sTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.sTypeId
     *
     * @param sTypeId the value for producttype.sTypeId
     *
     * @mbggenerated
     */
    public void setsTypeId(String sTypeId) {
        this.sTypeId = sTypeId == null ? null : sTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.Attribute_70
     *
     * @return the value of producttype.Attribute_70
     *
     * @mbggenerated
     */
    public String getAttribute_70() {
        return attribute_70;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.Attribute_70
     *
     * @param attribute_70 the value for producttype.Attribute_70
     *
     * @mbggenerated
     */
    public void setAttribute_70(String attribute_70) {
        this.attribute_70 = attribute_70 == null ? null : attribute_70.trim();
    }
}