package com.jkoss.pojo;

public class Productimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.productImageId
     *
     * @mbggenerated
     */
    private Integer productImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.piProductId
     *
     * @mbggenerated
     */
    private Integer piProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.imageType
     *
     * @mbggenerated
     */
    private String imageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.Attribute_75
     *
     * @mbggenerated
     */
    private String attribute_75;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.productImageId
     *
     * @return the value of productimage.productImageId
     *
     * @mbggenerated
     */
    public Integer getProductImageId() {
        return productImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.productImageId
     *
     * @param productImageId the value for productimage.productImageId
     *
     * @mbggenerated
     */
    public void setProductImageId(Integer productImageId) {
        this.productImageId = productImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.piProductId
     *
     * @return the value of productimage.piProductId
     *
     * @mbggenerated
     */
    public Integer getPiProductId() {
        return piProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.piProductId
     *
     * @param piProductId the value for productimage.piProductId
     *
     * @mbggenerated
     */
    public void setPiProductId(Integer piProductId) {
        this.piProductId = piProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.image
     *
     * @return the value of productimage.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.image
     *
     * @param image the value for productimage.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.imageType
     *
     * @return the value of productimage.imageType
     *
     * @mbggenerated
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.imageType
     *
     * @param imageType the value for productimage.imageType
     *
     * @mbggenerated
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.Attribute_75
     *
     * @return the value of productimage.Attribute_75
     *
     * @mbggenerated
     */
    public String getAttribute_75() {
        return attribute_75;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.Attribute_75
     *
     * @param attribute_75 the value for productimage.Attribute_75
     *
     * @mbggenerated
     */
    public void setAttribute_75(String attribute_75) {
        this.attribute_75 = attribute_75 == null ? null : attribute_75.trim();
    }
}