package com.jkoss.pojo;

public class Product {
   
    private Integer productId;


    private String productName;

  
    private Integer productPrice;

    
    private Integer singlePrice;

  
    private String productRealPrice;


    private String productTitle;

    
    private Integer productType;


    private Integer productBrand;


    private String headImage;

   
    private Integer status;

 
    private String style;

   
    private String attribute_71;


    private String productDetail;


    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }


    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

 
    public Integer getProductPrice() {
        return productPrice;
    }


    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }


    public Integer getSinglePrice() {
        return singlePrice;
    }


    public void setSinglePrice(Integer singlePrice) {
        this.singlePrice = singlePrice;
    }


    public String getProductRealPrice() {
        return productRealPrice;
    }

   
    public void setProductRealPrice(String productRealPrice) {
        this.productRealPrice = productRealPrice == null ? null : productRealPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productTitle
     *
     * @return the value of product.productTitle
     *
     * @mbggenerated
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productTitle
     *
     * @param productTitle the value for product.productTitle
     *
     * @mbggenerated
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle == null ? null : productTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productType
     *
     * @return the value of product.productType
     *
     * @mbggenerated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productType
     *
     * @param productType the value for product.productType
     *
     * @mbggenerated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productBrand
     *
     * @return the value of product.productBrand
     *
     * @mbggenerated
     */
    public Integer getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productBrand
     *
     * @param productBrand the value for product.productBrand
     *
     * @mbggenerated
     */
    public void setProductBrand(Integer productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.headImage
     *
     * @return the value of product.headImage
     *
     * @mbggenerated
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.headImage
     *
     * @param headImage the value for product.headImage
     *
     * @mbggenerated
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage == null ? null : headImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.style
     *
     * @return the value of product.style
     *
     * @mbggenerated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.style
     *
     * @param style the value for product.style
     *
     * @mbggenerated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Attribute_71
     *
     * @return the value of product.Attribute_71
     *
     * @mbggenerated
     */
    public String getAttribute_71() {
        return attribute_71;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Attribute_71
     *
     * @param attribute_71 the value for product.Attribute_71
     *
     * @mbggenerated
     */
    public void setAttribute_71(String attribute_71) {
        this.attribute_71 = attribute_71 == null ? null : attribute_71.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productDetail
     *
     * @return the value of product.productDetail
     *
     * @mbggenerated
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productDetail
     *
     * @param productDetail the value for product.productDetail
     *
     * @mbggenerated
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail == null ? null : productDetail.trim();
    }
}