package com.jkoss.pojo;

import java.math.BigDecimal;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPwd
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.changePwdNo
     *
     * @mbggenerated
     */
    private String changePwdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.changePwdTime
     *
     * @mbggenerated
     */
    private String changePwdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.realName
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cardNo
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobilePhone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobileCheck
     *
     * @mbggenerated
     */
    private String mobileCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mailCheck
     *
     * @mbggenerated
     */
    private String mailCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.faceImg
     *
     * @mbggenerated
     */
    private String faceImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.postNo
     *
     * @mbggenerated
     */
    private String postNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip_address
     *
     * @mbggenerated
     */
    private String ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip_location
     *
     * @mbggenerated
     */
    private String ip_location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.oldIpAddress
     *
     * @mbggenerated
     */
    private String oldIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.marital_status
     *
     * @mbggenerated
     */
    private String marital_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Monthly_income
     *
     * @mbggenerated
     */
    private String monthly_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Attribute_22
     *
     * @mbggenerated
     */
    private String attribute_22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.oldDate
     *
     * @mbggenerated
     */
    private String oldDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.newDate
     *
     * @mbggenerated
     */
    private String newDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userType
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.experience
     *
     * @mbggenerated
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite
     *
     * @mbggenerated
     */
    private Integer invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.commissionCount
     *
     * @mbggenerated
     */
    private Double commissionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.commissionBalance
     *
     * @mbggenerated
     */
    private Double commissionBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.commissionMention
     *
     * @mbggenerated
     */
    private Double commissionMention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.commissionPoints
     *
     * @mbggenerated
     */
    private Integer commissionPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Interests
     *
     * @mbggenerated
     */
    private String interests;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userId the value for user.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param userName the value for user.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPwd
     *
     * @return the value of user.userPwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPwd
     *
     * @param userPwd the value for user.userPwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.changePwdNo
     *
     * @return the value of user.changePwdNo
     *
     * @mbggenerated
     */
    public String getChangePwdNo() {
        return changePwdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.changePwdNo
     *
     * @param changePwdNo the value for user.changePwdNo
     *
     * @mbggenerated
     */
    public void setChangePwdNo(String changePwdNo) {
        this.changePwdNo = changePwdNo == null ? null : changePwdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.changePwdTime
     *
     * @return the value of user.changePwdTime
     *
     * @mbggenerated
     */
    public String getChangePwdTime() {
        return changePwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.changePwdTime
     *
     * @param changePwdTime the value for user.changePwdTime
     *
     * @mbggenerated
     */
    public void setChangePwdTime(String changePwdTime) {
        this.changePwdTime = changePwdTime == null ? null : changePwdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.realName
     *
     * @return the value of user.realName
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.realName
     *
     * @param realName the value for user.realName
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cardNo
     *
     * @return the value of user.cardNo
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cardNo
     *
     * @param cardNo the value for user.cardNo
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobilePhone
     *
     * @return the value of user.mobilePhone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobilePhone
     *
     * @param mobilePhone the value for user.mobilePhone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobileCheck
     *
     * @return the value of user.mobileCheck
     *
     * @mbggenerated
     */
    public String getMobileCheck() {
        return mobileCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobileCheck
     *
     * @param mobileCheck the value for user.mobileCheck
     *
     * @mbggenerated
     */
    public void setMobileCheck(String mobileCheck) {
        this.mobileCheck = mobileCheck == null ? null : mobileCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mail
     *
     * @return the value of user.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mail
     *
     * @param mail the value for user.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mailCheck
     *
     * @return the value of user.mailCheck
     *
     * @mbggenerated
     */
    public String getMailCheck() {
        return mailCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mailCheck
     *
     * @param mailCheck the value for user.mailCheck
     *
     * @mbggenerated
     */
    public void setMailCheck(String mailCheck) {
        this.mailCheck = mailCheck == null ? null : mailCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.faceImg
     *
     * @return the value of user.faceImg
     *
     * @mbggenerated
     */
    public String getFaceImg() {
        return faceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.faceImg
     *
     * @param faceImg the value for user.faceImg
     *
     * @mbggenerated
     */
    public void setFaceImg(String faceImg) {
        this.faceImg = faceImg == null ? null : faceImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.postNo
     *
     * @return the value of user.postNo
     *
     * @mbggenerated
     */
    public String getPostNo() {
        return postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.postNo
     *
     * @param postNo the value for user.postNo
     *
     * @mbggenerated
     */
    public void setPostNo(String postNo) {
        this.postNo = postNo == null ? null : postNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip_address
     *
     * @return the value of user.ip_address
     *
     * @mbggenerated
     */
    public String getIp_address() {
        return ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip_address
     *
     * @param ip_address the value for user.ip_address
     *
     * @mbggenerated
     */
    public void setIp_address(String ip_address) {
        this.ip_address = ip_address == null ? null : ip_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip_location
     *
     * @return the value of user.ip_location
     *
     * @mbggenerated
     */
    public String getIp_location() {
        return ip_location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip_location
     *
     * @param ip_location the value for user.ip_location
     *
     * @mbggenerated
     */
    public void setIp_location(String ip_location) {
        this.ip_location = ip_location == null ? null : ip_location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.oldIpAddress
     *
     * @return the value of user.oldIpAddress
     *
     * @mbggenerated
     */
    public String getOldIpAddress() {
        return oldIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.oldIpAddress
     *
     * @param oldIpAddress the value for user.oldIpAddress
     *
     * @mbggenerated
     */
    public void setOldIpAddress(String oldIpAddress) {
        this.oldIpAddress = oldIpAddress == null ? null : oldIpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.marital_status
     *
     * @return the value of user.marital_status
     *
     * @mbggenerated
     */
    public String getMarital_status() {
        return marital_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.marital_status
     *
     * @param marital_status the value for user.marital_status
     *
     * @mbggenerated
     */
    public void setMarital_status(String marital_status) {
        this.marital_status = marital_status == null ? null : marital_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Monthly_income
     *
     * @return the value of user.Monthly_income
     *
     * @mbggenerated
     */
    public String getMonthly_income() {
        return monthly_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Monthly_income
     *
     * @param monthly_income the value for user.Monthly_income
     *
     * @mbggenerated
     */
    public void setMonthly_income(String monthly_income) {
        this.monthly_income = monthly_income == null ? null : monthly_income.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Attribute_22
     *
     * @return the value of user.Attribute_22
     *
     * @mbggenerated
     */
    public String getAttribute_22() {
        return attribute_22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Attribute_22
     *
     * @param attribute_22 the value for user.Attribute_22
     *
     * @mbggenerated
     */
    public void setAttribute_22(String attribute_22) {
        this.attribute_22 = attribute_22 == null ? null : attribute_22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.oldDate
     *
     * @return the value of user.oldDate
     *
     * @mbggenerated
     */
    public String getOldDate() {
        return oldDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.oldDate
     *
     * @param oldDate the value for user.oldDate
     *
     * @mbggenerated
     */
    public void setOldDate(String oldDate) {
        this.oldDate = oldDate == null ? null : oldDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.newDate
     *
     * @return the value of user.newDate
     *
     * @mbggenerated
     */
    public String getNewDate() {
        return newDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.newDate
     *
     * @param newDate the value for user.newDate
     *
     * @mbggenerated
     */
    public void setNewDate(String newDate) {
        this.newDate = newDate == null ? null : newDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.balance
     *
     * @return the value of user.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.balance
     *
     * @param balance the value for user.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userType
     *
     * @return the value of user.userType
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userType
     *
     * @param userType the value for user.userType
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.experience
     *
     * @return the value of user.experience
     *
     * @mbggenerated
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.experience
     *
     * @param experience the value for user.experience
     *
     * @mbggenerated
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.signature
     *
     * @return the value of user.signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.signature
     *
     * @param signature the value for user.signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite
     *
     * @return the value of user.invite
     *
     * @mbggenerated
     */
    public Integer getInvite() {
        return invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite
     *
     * @param invite the value for user.invite
     *
     * @mbggenerated
     */
    public void setInvite(Integer invite) {
        this.invite = invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.commissionCount
     *
     * @return the value of user.commissionCount
     *
     * @mbggenerated
     */
    public Double getCommissionCount() {
        return commissionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.commissionCount
     *
     * @param commissionCount the value for user.commissionCount
     *
     * @mbggenerated
     */
    public void setCommissionCount(Double commissionCount) {
        this.commissionCount = commissionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.commissionBalance
     *
     * @return the value of user.commissionBalance
     *
     * @mbggenerated
     */
    public Double getCommissionBalance() {
        return commissionBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.commissionBalance
     *
     * @param commissionBalance the value for user.commissionBalance
     *
     * @mbggenerated
     */
    public void setCommissionBalance(Double commissionBalance) {
        this.commissionBalance = commissionBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.commissionMention
     *
     * @return the value of user.commissionMention
     *
     * @mbggenerated
     */
    public Double getCommissionMention() {
        return commissionMention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.commissionMention
     *
     * @param commissionMention the value for user.commissionMention
     *
     * @mbggenerated
     */
    public void setCommissionMention(Double commissionMention) {
        this.commissionMention = commissionMention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.commissionPoints
     *
     * @return the value of user.commissionPoints
     *
     * @mbggenerated
     */
    public Integer getCommissionPoints() {
        return commissionPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.commissionPoints
     *
     * @param commissionPoints the value for user.commissionPoints
     *
     * @mbggenerated
     */
    public void setCommissionPoints(Integer commissionPoints) {
        this.commissionPoints = commissionPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Interests
     *
     * @return the value of user.Interests
     *
     * @mbggenerated
     */
    public String getInterests() {
        return interests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Interests
     *
     * @param interests the value for user.Interests
     *
     * @mbggenerated
     */
    public void setInterests(String interests) {
        this.interests = interests == null ? null : interests.trim();
    }
}