package com.jkoss.pojo;

public class Visitors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.visitorsId
     *
     * @mbggenerated
     */
    private Integer visitorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.id
     *
     * @return the value of visitors.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.id
     *
     * @param id the value for visitors.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.uid
     *
     * @return the value of visitors.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.uid
     *
     * @param uid the value for visitors.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.visitorsId
     *
     * @return the value of visitors.visitorsId
     *
     * @mbggenerated
     */
    public Integer getVisitorsId() {
        return visitorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.visitorsId
     *
     * @param visitorsId the value for visitors.visitorsId
     *
     * @mbggenerated
     */
    public void setVisitorsId(Integer visitorsId) {
        this.visitorsId = visitorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.date
     *
     * @return the value of visitors.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.date
     *
     * @param date the value for visitors.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.address
     *
     * @return the value of visitors.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.address
     *
     * @param address the value for visitors.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}