package com.jkoss.dao;

import com.jkoss.pojo.Producttype;

public interface ProducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    int insert(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    int insertSelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    Producttype selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Producttype record);
}