package com.jkoss.dao;

import com.jkoss.pojo.Userbyaddress;

public interface UserbyaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    int insert(Userbyaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    int insertSelective(Userbyaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    Userbyaddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userbyaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbyaddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userbyaddress record);
}