package com.jkoss.dao;

import com.jkoss.pojo.Visitors;

public interface VisitorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    int insert(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    int insertSelective(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    Visitors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Visitors record);
}